import:
  - ~/.config/alacritty/themes/themes/breeze.yaml

scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  #history: 10000

  # Scrolling distance multiplier.
  multiplier: 3

# Font configuration
font:
  normal:
    family: MonaspiceNe Nerd Font Mono
    style: Light

  bold:
    style: Medium

  size: 16.0

draw_bold_text_with_bright_colors: false

key_bindings:
  - { key: Left,     mods: Command, chars: "\x1bOH"                      }
  - { key: Right,    mods: Command, chars: "\x1bOF"                      }
  - { key: Home,                    chars: "\x1bOH",   mode: AppCursor   }
  - { key: End,                     chars: "\x1bOF",   mode: AppCursor   }
  - { key: Left,     mods: Alt,     chars: "\x1bb"                       }
  - { key: Right,    mods: Alt,     chars: "\x1bf"                       }
  - { key: N,        mods: Command, action: SpawnNewInstance }
  - { key: Q,        mods: Command, action: Quit }
