import = ["/Users/karim/.config/alacritty/themes/themes/breeze.yaml"]

[colors]
draw_bold_text_with_bright_colors = false

[font]
size = 16.0

[font.bold]
style = "Medium"

[font.normal]
family = "MonaspiceNe Nerd Font Mono"
style = "Light"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Home"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "End"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[scrolling]
multiplier = 3
